AUTHORS.rst, CHANGES.rst, README.rst, RELEASE-NOTES.rst, docs/conf.py, invenio_search/__init__.py, invenio_search/version.py, setup.py
=> Invenio-Search v0.1.0

invenio_search/upgrades/search_2014_07_21_facets_per_collection.py, invenio_search/upgrades/search_2015_03_03_fix_models.py
* FIX: import of invenio_upgrader
Signed-off-by: Eamonn Maguire eamonnmag@gmail.com
=> global: fix import of invenio_upgrader

CHANGES.rst, RELEASE-NOTES.rst, invenio_search/translations/de/LC_MESSAGES/messages.po, invenio_search/translations/es/LC_MESSAGES/messages.po, invenio_search/translations/fr/LC_MESSAGES/messages.po, invenio_search/translations/invenio.pot, invenio_search/translations/it/LC_MESSAGES/messages.po, invenio_search/version.py, setup.cfg
=> Invenio-Search v0.1.1

invenio_search/forms.py, requirements-devel.txt, setup.py
* Adds invenio-knowledge to the requirement set.
* Fixes import after separation of the invenio_knowledge module.
Signed-off-by: Marco Neumann <marco@crepererum.net>
=> global: invenio-knowledge dependency fix

CHANGES.rst, README.rst, RELEASE-NOTES.rst, invenio_search/translations/de/LC_MESSAGES/messages.po, invenio_search/translations/es/LC_MESSAGES/messages.po, invenio_search/translations/fr/LC_MESSAGES/messages.po, invenio_search/translations/invenio.pot, invenio_search/translations/it/LC_MESSAGES/messages.po, invenio_search/version.py
=> Invenio-Search v0.1.2

.travis.invenio.cfg, .travis.yml, setup.py
=> travis: fix environment creation

CHANGES.rst, RELEASE-NOTES.rst, invenio_search/version.py, setup.py
=> Invenio-Search v0.1.4

CHANGES.rst, RELEASE-NOTES.rst, invenio_search/version.py
=> Invenio-Search v0.1.5

invenio_search/static/css/search/search.css, invenio_search/static/js/search/facets_menu.js, invenio_search/templates/search/search_base.html
* BETTER Improves facet list interface and usability (closes #23).
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> search: facet list interface

.gitignore, CHANGES.rst, RELEASE-NOTES.rst, invenio_search/version.py
=> Invenio-Search v1.0.0a1

examples/app.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> examples: fix typo

.editorconfig, .travis.yml, docs/api.rst, invenio_search/config.py, invenio_search/contrib/records.py, invenio_search/ext.py, invenio_search/utils.py, setup.py, tests/conftest.py, tests/test_contrib_records.py, tests/test_invenio_search.py
=> global: index guessing from schema

invenio_search/version.py
=> version: post-release bump

examples/app.py
* Updates documentation of accounts cli usage.
(addresses inveniosoftware/invenio-accounts#90)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> global: update of example documentation

invenio_search/config.py, setup.py
* Adds InvenioSearch to API application.
* Removes unused configuration options.
=> global: entrypoint and config fix

CHANGES.rst, RELEASE-NOTES.rst, invenio_search/version.py
=> release: v1.0.0a4

MANIFEST.in, invenio_search/config.py, setup.py, tests/data/records/authorities/notajson, tests/test_invenio_search.py
* Removes reading default variables from environment variables.
(closes #51)
=> config: environment variable use removal

invenio_search/cli.py
* Fixes help text. (closes #59)
=> cli: help text fix

invenio_search/config.py
=> config: allowed keywords list

CHANGES.rst, RELEASE-NOTES.rst, invenio_search/version.py
Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>
=> release: v1.0.0a5

CHANGES.rst, RELEASE-NOTES.rst, invenio_search/api.py, invenio_search/version.py
=> api: doc type fix

CHANGES.rst, RELEASE-NOTES.rst, invenio_search/version.py
=> release: v1.0.0a7

docs/api.rst, invenio_search/api.py, invenio_search/ext.py, invenio_search/utils.py
* Improves documentation. (addresses #75)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> docs: addition of param and result sections

.travis.yml, examples/app-fixtures.sh, examples/app-setup.sh, examples/app-teardown.sh, examples/app.py, examples/requirements.txt, tests/test_examples_app.py
* Adds test_examples_app.py. (closes #80)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> tests: addition of test_examples_app.py

MANIFEST.in, README.rst, RELEASE-NOTES.rst, docs/requirements.txt, invenio_search/config.py
=> docs: move to readthedocs.io

CHANGES.rst, RELEASE-NOTES.rst, invenio_search/version.py
=> release: v1.0.0a8

CHANGES.rst, RELEASE-NOTES.rst, invenio_search/version.py, setup.py
=> release: v1.0.0a9

.editorconfig, .gitignore, INSTALL.rst, MANIFEST.in, docs/Makefile, docs/conf.py, docs/configuration.rst, docs/examplesapp.rst, docs/index.rst, docs/make.bat, invenio_search/config.py, setup.cfg, setup.py, tests/test_examples_app.py
* FIX Adds changes according to release preparation checklist.
* FIX Pins elasticsearch-dsl to less than 5.1.0 due to change
in Response class constructor signature. (addresses #96)
Signed-off-by: Paulina Lach <paulina.malgorzata.lach@cern.ch>
Co-authored-by: Diego Rodriguez <diego.rodriguez@cern.ch>
=> global: release checklist

CHANGES.rst, RELEASE-NOTES.rst, invenio_search/version.py
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> release: v1.0.0a10

README.rst, docs/examplesapp.rst, examples/app-setup.sh, examples/app.py, invenio_search/__init__.py, invenio_search/ext.py, run-tests.sh, tests/test_examples_app.py
Draft of the documentation that I'm still refining.
=> update for documentation

invenio_search/ext.py, tests/conftest.py, tests/mock_module/templates/__init__.py, tests/mock_module/templates/v2/record-view-v1.json, tests/mock_module/templates/v2/subdirectory/file-download-v1.json, tests/mock_module/templates/v5/__init__.py, tests/mock_module/templates/v5/record-view-v5.json, tests/test_cli.py, tests/test_invenio_search.py
* FIXES path format for templates to support dot notation 
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>
=> cli: template path format change

invenio_search/cli.py
Signed-off-by: David Caro <david@dcaro.es>
=> cli: remove unused import

.editorconfig, requirements-devel.txt, setup.py
* Removes invenio-query-parser as a dependence. (addresses #130)
=> installation: invenio-query-parser removal

CHANGES.rst
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> global: updated CHANGES.rst file

invenio_search/api.py, invenio_search/config.py, invenio_search/ext.py, invenio_search/utils.py, setup.py, tests/conftest.py, tests/mock_module/templates/v2/record-view-v1.json, tests/mock_module/templates/v2/subdirectory/file-download-v1.json, tests/mock_module/templates/v5/record-view-v5.json, tests/mock_module/templates/v6/record-view-v6.json, tests/test_invenio_search.py, tests/test_utils.py
I have created a new PR takin David commit and adding a few changes on top.
See comments in the previous pr: https://github.com/inveniosoftware/invenio-search/pull/145
=> Allow prefixing indices

invenio_search/ext.py
=> ext: adding deprecation warning for Elasticsearch v2

invenio_search/ext.py, tests/test_invenio_search.py
=> ext: fix active_aliases with mapping and prefix

invenio_search/api.py
=> api: substitute '_all' with '*'

.travis.yml
Bump Elasticsearch version as requested in inveniosoftware/invenio#3961.
=> travis: bump Elasticsearch version

.travis.yml, examples/app.py, requirements-devel.txt, setup.py
* drop support for python 2.7
* update travis.yml
* fix tests
* closes #195
=> global: manage flask dependency by invenio-base

CHANGES.rst, docs/conf.py, invenio_search/api.py, invenio_search/version.py, pytest.ini, run-tests.sh, setup.py, tests/conftest.py, tests/test_query.py
- close https://github.com/inveniosoftware/invenio-records-resources/issues/122
- make new release so that invenio-records-resource can use it
=> api: set preference param externally + version bump

CHANGES.rst, invenio_search/__init__.py
:heart: Thank you for your contribution!
> Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> release: v2.4.1
