invenio_search/services.py

* Fixes one more `invenio-knowledge` import that slipped in
8761850b100bd92f268ff542a73e7841d8643837.

installation: more invenio-knowledge import fixes

---

AUTHORS.rst
invenio_search/utils.py
requirements-devel.txt
setup.py

* Adds missing `invenio_access` dependency and amends past upgrade
recipes following its separation into standalone package.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>

installation: fix invenio_access imports

---

.travis.invenio.cfg
invenio_search/api.py
invenio_search/bundles.py
invenio_search/cache.py
invenio_search/enhancers/collection_filter.py
invenio_search/facet_builders.py
invenio_search/forms.py
invenio_search/models.py
invenio_search/searchext/services/CollectionNameSearchService.py
invenio_search/searchext/services/FAQKBService.py
invenio_search/searchext/services/JournalHintService.py
invenio_search/searchext/services/LHCBeamStatusService.py
invenio_search/services.py
invenio_search/user_settings.py
invenio_search/utils.py
invenio_search/views/search.py
invenio_search/walkers/elasticsearch.py
invenio_search/washers.py
requirements-devel.txt
setup.py

* FIX Adds missing `invenio_base` dependency and amends past
upgrade recipes following its separation into standalone package.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>

installation: fix invenio_base imports

---

setup.py

* FIX Adds `requests` dependency that is explicitly required for
`elasticsearch.connection.RequestsHttpConnection` transport class.

installation: explicit `requests` dependency

---

examples/app.py

* Fixes the creation of the user since the `users` CLI now requires `-e`
parameter to specify the email.
* Fixes the check of registered user.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

examples: fix steps in documentation

---

examples/app.py
invenio_search/ext.py
tests/test_invenio_search.py

* Adds method for flushing and refreshing one or more indices during
tests.
* Fixes some PEP8/257 errors.

ext: flush and refresh indices

---

RELEASE-NOTES.rst
examples/app.py
setup.cfg
setup.py

* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).

global: inveniosoftware.org

---

MANIFEST.in
invenio_search/cli.py
invenio_search/ext.py
tests/conftest.py
tests/data/templates/file_download_v1.json
tests/data/templates/record_view_v1.json
tests/data/templates/subdirectory/file_download_v1.json
tests/test_cli.py
tests/test_invenio_search.py

- ADDS to the `index init` command the registration of the
ES templates, loaded from the entrypoint 'invenio_search.templates'
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>

cli: registration of ES templates

---

invenio_search/api.py
tests/test_query.py

* When creating a RecordsSearch instance with a default filter, i.e. a
`bool` query with a `filter`, `minimum_should_match` should be
explicitly set, otherwise a document will match the bool query even if
none of the `should` queries match, according to `bool`
query documentation.
Signed-off-by: Chris Aslanoglou <chris.aslanoglou@gmail.com>
---
You can see more info on what motivated this PR, here: inspirehep/inspire-next#2829.

api: use minimum_should_match: 1 in filter context

---

invenio_search/api.py
run-tests.sh
tests/test_query.py

* added a method to RecordsSearch to return a new instance of Search
with a new query param preference. The value of the param will not
change for requests coming from the same user.
* closes #106

api: added preference param to eliminate ES bouncing issue

---

.travis.yml
invenio_search/cli.py
tests/test_cli.py

* Fixes output format of `index list` which was broken in a previous
commit (possibly 9daeadb97dc72e713ff3d5b29e0feb3ac778985c)
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>

cli: fix output format of `index list`

---

setup.py

* Fixes issue that would cause Invenio installation to break everytime
new versions of idna and urllib3 were being released, since
elasticsearch and requests specify hard dependencies on these modules.

installation: idna/urllib3 dependency resolution

---

setup.py
tests/test_cli.py

* Adds upper limit to elasticsearch-dsl < 6.2.0, because of breaking changes in empty query handling.
Closes #149 
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>

installation: limit elasticsearch-dsl<6.2.0

---

docs/conf.py
invenio_search/config.py
invenio_search/ext.py
tests/test_invenio_search.py

* Adds the "SEARCH_CLIENT_CONFIG" config variable, allowing more
flexibility for the Elasticsearch client initialization (closes #82)

config: add SEARCH_CLIENT_CONFIG variable

---

docs/configuration.rst
invenio_search/config.py
invenio_search/ext.py
tests/test_invenio_search.py

* Improves documentation of the configuration options, in particular with respect to the Elasticsearch client configuration (closes inveniosoftware/invenio#3936)
* Changes the default connection class from requests to urllib3, which is the default recommended class by Elasticsearch. See https://elasticsearch-py.readthedocs.io/en/master/transports.html. The change seems to be backward compatible as all options provided by the requests connection class is also supported by urllib3 connection class.

docs: improved configuration section

---

.travis.yml
examples/app-teardown.sh
invenio_search/api.py
invenio_search/cli.py
invenio_search/errors.py
invenio_search/ext.py
invenio_search/utils.py
setup.py
tests/conftest.py
tests/test_cli.py
tests/test_invenio_search.py
tests/test_utils.py

The suffix is a timestamp and will be added to new indices. An alias
will be created with the same name as the index without the suffix.
Closes #162.

ext: add suffix to index names

---

CHANGES.rst
invenio_search/ext.py
invenio_search/version.py
tests/test_invenio_search.py

Currently there is no way to run create to add missing indexes and it's not possible to create/delete only specified indexes through invenio-search API.
This PR if fixing this problem.
* Adds option `ignore_existing` which is ignoring indexes which are already in ES.
* Adds option to create/delete only selected indexes.

invenio_search: Add ignore_existing option to create.

---

INSTALL.rst
README.rst
docs/configuration.rst
invenio_search/__init__.py

* Fixes references to older versions of Elasticsearch
* Fixes index and alias graph
* Minor grammar changes
Closes #188

docs: fix references to older versions of ES

---

CHANGES.rst
invenio_search/version.py
setup.py

elasticsearch-py product check will make any invenio-search/indexer operation fail. Therefore we need to pin it down. As stated [here](https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883368588) there will be no more releases of the OSS version.
Note the fix might be needed for older releases although according to the EOL, v3.3 is out of support so it should be good since this would be picked by invenio v3.4.0 and v3.4.1

release: v1.4.2

---

.github/workflows/tests.yml
invenio_search/ext.py

Using `with self.app.app_context():` closes the current DB session on `__exit__`, causing a `sqlalchemy.orm.exc.DetachedInstanceError` when accessing any property of the object expected in the session. This error occurs only the first time index_templates are loaded, such as when indexing the very first record.
Subsequent accesses won't trigger this issue due to the @cached_property, preventing reloading of index_templates.
Bonus 👀: using [Conventional Commits](https://www.conventionalcommits.org)

fix: avoid closing db session
